FROM node:18-alpine

WORKDIR /app

# Копируем зависимости
COPY package*.json ./
RUN npm install

# Копируем код
COPY . .

# Порт для разработки
EXPOSE 3000

# Запускаем dev сервер
CMD ["npm", "start"]